//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HipchatScraper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public string id { get; set; }
        public System.DateTimeOffset date { get; set; }
        public long from_id { get; set; }
        public string from_name { get; set; }
        public string message1 { get; set; }
        public string raw { get; set; }
        public string file_name { get; set; }
        public Nullable<long> file_size { get; set; }
        public string file_url { get; set; }
        public Nullable<long> room_id { get; set; }
    }
}
