//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HipchatScraper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public long room_id { get; set; }
        public string name { get; set; }
        public string privacy { get; set; }
        public Nullable<long> messages_sent { get; set; }
        public Nullable<System.DateTimeOffset> last_active { get; set; }
    }
}
